### PR TITLE
multistep

### PR DESCRIPTION
**Pull request by yomichi**
When `base_input_dir` is a list with two or more directories, the "multistep" runner is invoked

### CODE REVIEW

**Comment by k-yoshimi** [comment]
@yomichi 
ありがとうございます。確認しました。

@skasamatsu 
問題なさそうですが、念の為笠松さんの方でも確認いただけるでしょうか？

**Comment by k-yoshimi** [comment]
@yomichi 
マニュアルにmulti_stepに関する変更が反映されていない気がするので、もしそうでしたら追記をお願いできるでしょうか？

**Comment by skasamatsu** [comment]
このエラーで死亡：

Traceback (most recent call last):
  File "/home/k0306/k030600/.pyenv/versions/abics_mydev/bin/abics", line 8, in <module>
    sys.exit(main())
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-2019.10/envs/abics_mydev/lib/python3.8/site-packages/abics/scripts/main.py", line 138, in main
    main_impl(tomlfile)
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-2019.10/envs/abics_mydev/lib/python3.8/site-packages/abics/scripts/main.py", line 122, in main_impl
    obs = RXcalc.run(
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-2019.10/envs/abics_mydev/lib/python3.8/site-packages/abics/mc_mpi.py", line 401, in run
    self.mycalc.energy = self.mycalc.model.energy(self.mycalc.config)
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-2019.10/envs/abics_mydev/lib/python3.8/site-packages/abics/applications/latgas_abinitio_interface/model_setup.py", line 202, in energy
    energy, structure = self.abinitio_run.submit(
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-2019.10/envs/abics_mydev/lib/python3.8/site-packages/abics/applications/latgas_abinitio_interface/run_base_mpi.py", line 223, in submit
    energy, newstructure = self.runners[i].submit(
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-2019.10/envs/abics_mydev/lib/python3.8/site-packages/abics/applications/latgas_abinitio_interface/run_base_mpi.py", line 148, in submit
    solverinput.update_info_by_structure(structure)
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-2019.10/envs/abics_mydev/lib/python3.8/site-packages/abics/applications/latgas_abinitio_interface/vasp.py", line 103, in update_info_by_structure
    self.pos_info = Poscar(structure=structure, selective_dynamics=structure.site_properties["seldyn"])
KeyError: 'seldyn'

**Comment by skasamatsu** [comment]
I'll look into this.

**Comment by skasamatsu** [comment]
@yomichi @k-yoshimi plz check

**Comment by k-yoshimi** [comment]
@yomichi 
Please check the bug fix reported by skasamatsu.
If there's no problem, please merge it.

**Pull request merged**
