### PR TITLE
add logging facility

### PR DESCRIPTION
**Pull request by aoymt**
Add logging facility that works with MPI parallel environment.

### CODE REVIEW

**Comment by yomichi** [comment]
`extra/loggers` won't be installed and not be available, so please move this under the `abics` directory.
I think it's better to place `extra/loggers` as `abics/loggers` and replace `extra.loggers` with `abics.loggers` in the codes.

**Comment by aoymt** [comment]
the location of the module has been changed, and the scripts modified accordingly.
thank you for the comment.

**Comment by yomichi** [comment]
(1)
`mpi_log="collect"` does not work due to a mismatch between file modes in python (str) and MPI (int)
(I guess that they use no longer "collect" but "workers").
A patch follows:

```
diff --git a/abics/loggers/loggers.py b/abics/loggers/loggers.py
index ef95b15..690dc73 100644
--- a/abics/loggers/loggers.py
+++ b/abics/loggers/loggers.py
@@ -84,7 +84,8 @@ class _MPIFileStream:
     def __init__(
         self, filename: "Path", MPI: "MPI", mode: str = "_MPI_APPEND_MODE"
     ) -> None:
-        self.stream = MPI.File.Open(MPI.COMM_WORLD, filename, mode)
+        mpi_mode = MPI.MODE_WRONLY | MPI.MODE_CREATE
+        self.stream = MPI.File.Open(MPI.COMM_WORLD, filename, mpi_mode)
         self.stream.Set_atomicity(True)
         self.name = "MPIfilestream"
 
@@ -243,7 +244,7 @@ def set_log_handles(
                 fh.setFormatter(FFORMATTER)
         elif mpi_log == "collect":
             rank = MPI.COMM_WORLD.Get_rank()
-            fh = _MPIHandler(log_path, MPI, mode=MPI.MODE_WRONLY | MPI.MODE_CREATE)
+            fh = _MPIHandler(log_path, MPI, mode="w")
             fh.addFilter(_MPIRankFilter(rank))
             fh.setFormatter(FFORMATTER_MPI)
         elif mpi_log == "workers":
```

(2)
Please add the following to `main_potts.py` also:

```
import logging
logger = logging.getLogger("main")
```

**Comment by aoymt** [comment]
thank you for the patch.

it seems that the original code works in my environment... I agree to the mismatch between mode: str in the code and amode: int of MPI.File.Open; but the actual mode parameter is given as MPI.MODE_* (defined as int), and type declaration may be nominal.

mpi_log="collect" and "workers" differ in handling of output files; in "collect" mode, logs from all ranks are gathered into a single file (specified by log_path= parameter) using shared MPI-IO, while in "workers" mode, logs from each rank are written to separate files with their filenames suffixed with rank numbers.

**Comment by yomichi** [comment]
Oops, I find that `logging.FileHandler`, the base class of `loggers._MPIHandler`, becomes to check whether `'b'` exists in `mode`, so the "collect" mode fails in Python 3.10.

By the way, `abics_train` fails when it invokes the MPI version of `train.x`, because we cannot invoke an MPI process (env) from another MPI process unless using `MPI_Comm_spawn`.
Please remove `mpi_log` from `set_log_handles` in `scripts/train.py` to use a serial logger.

**Comment by aoymt** [comment]
alas. one choice is to change the base class of loggers._MPIHandler form FileHandler to StreamHandler (superclass of FileHandler). another one is to pass fake mode to FileHandler in constructor. the latter may be simpler.

**Comment by yomichi** [comment]
I just make sure that the current code works both for Python 3.9 and 3.10. I think it's ready to merge.
If OK, please merge it!

**Pull request merged**
