### PR TITLE
New solver (`aenetPyLammps`): aenet via LAMMPS python package

### PR DESCRIPTION
**Pull request by yomichi**
`aenetPyLammps` is a new solver for evaluating an aenet NN potential through LAMMPS python package with the help of [aenet-lammps package](https://github.com/HidekiMori-CIT/aenet-lammps).
It is expected to be faster than the old `aenet` solver because it does not spawn any subprocesses and reads an input file only once.

Example of the input parameters:

``` toml
[sampling.solver]
type = 'aenetPyLammps'
base_input_dir = ['./baseinput']
perturb = 0.0
run_scheme = 'function'
ignore_species = ["O"]
```

NN potential should be specified via a LAMMPS input file `baseinput/in.lammps` as follows:

```
pair_style      aenet
pair_coeff      * * v00 Al Mg 15t-15t.nn Al Mg
neighbor        0.1 bin
```

Other commands (e.g., `run`) will be constructed by abICS.

### CODE REVIEW

**Comment by skasamatsu** [comment]
Right now abics_sampling dies without any error message if there is something wrong in in.lammps, so we need to do something about it.

**Comment by skasamatsu** [comment]
It seems lammps needs to be compiled with support for throwing exceptions when used as a library. See https://docs.lammps.org/Build_settings.html#exception-handling-when-using-lammps-as-a-library 
Sec. 3.5.8

**Comment by skasamatsu** [comment]
Confirmed that compiling lammps shared library with LMP_INC = -DLAMMPS_EXCEPTIONS in the makefile results in exceptions being raised instead of silently dying. It might be a good idea to note this fact in the install documentation.

**Comment by yomichi** [comment]
@skasamatsu 
thank you, I added a note to the docs.

**Pull request merged**
